<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerETz218p\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerETz218p/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerETz218p.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerETz218p\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerETz218p\App_KernelTestDebugContainer([
    'container.build_hash' => 'ETz218p',
    'container.build_id' => '8d0bbfd9',
    'container.build_time' => 1640516995,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerETz218p');
