<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGxwxm2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGxwxm2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGxwxm2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGxwxm2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTGxwxm2\App_KernelDevDebugContainer([
    'container.build_hash' => 'TGxwxm2',
    'container.build_id' => '996fe3f1',
    'container.build_time' => 1640515373,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGxwxm2');
