<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZUIaiUx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZUIaiUx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZUIaiUx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZUIaiUx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZUIaiUx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZUIaiUx',
    'container.build_id' => '4c4bd793',
    'container.build_time' => 1640521613,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZUIaiUx');
