name: CI

on:
  push:
  pull_request:

jobs:
  build-back:
    name: Build back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: shivammathur/setup-php@2.16.0

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        run: SYMFONY_DEPRECATIONS_HELPER='max[total]=5&max[self]=0&max[direct]=0&max[indirect]=5' php ./vendor/bin/phpunit
  
  build-front:
    name: Build front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd perudo-web && yarn && yarn test && yarn build

  deploy-back:
    needs: build-back
    name: Deploy back
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hidden-ravine-52418"
          heroku_email: "alexandre.bignalet@gmail.com"
  
  deploy-front:
    needs: build-front
    name: Deploy front
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      REACT_APP_BACK_END_URL: ${{ secrets.REACT_APP_BACK_END_URL }}
      REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd perudo-web && yarn && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AB_PERUDO_GAME }}"
          projectId: ab-perudo-game
          channelId: live
      
