name: CI

on:
    push:
    pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - uses: shivammathur/setup-php@2.16.0
            - name: Run tests
              run: php ./vendor/bin/phpunit
